### PR TITLE
Remove OpenJFX dependencies while publishing to Maven Central

### PR DESCRIPTION
**Pull request by Glavo**
Adding this configuration removes the transitive dependency on OpenJFX.

### CODE REVIEW

**Comment by Glavo** [comment]
I try to run the tests, but even before I make changes, many of them fail with IllegalAccessError……Fortunately, this modification didn't break any more tests, and it shouldn't have any breaking changes.

**Comment by palexdev** [comment]
Very interesting, I didn't know about that configuration

I'll test it as soon as possible and let you know

**Comment by palexdev** [comment]
@Glavo 
Seems like it will require some deep testing as I cannot make it work
When I add the "compileOnly" configuration strange things happen
image
As you can see from the image, on the left for some reason javafx 11 is downloaded and added as a dependency but the jars are empty. On the bottom the demo run fails stating that it cannot find the javafx.swing module

**Comment by Glavo** [comment]
> @Glavo Seems like it will require some deep testing as I cannot make it work When I add the "compileOnly" configuration strange things happen image As you can see from the image, on the left for some reason javafx 11 is downloaded and added as a dependency but the jars are empty. On the bottom the demo run fails stating that it cannot find the javafx.swing module

Oh, I'm tracking #140 right now (since I'm Chinese, this problem is serious for me), I'll keep working on that later.

**Comment by Glavo** [comment]
@palexdev I checked and fixed some issues.

JavaFX 11 is a transitive dependency brought by CssFX, I exclude this dependency now.

Another problem is that both the run classpath and the test classpath of the subproject `demo` require JavaFX, so `compileOnly` should not be applied to it. I also fixed this issue.

The last issue is that [VirtualizedFX](https://github.com/palexdev/VirtualizedFX) also comes with a runtime dependency on OpenJFX, which may be something you need to solve. After updating the configuration of the JavaFX plugin, you should be able to pass a dependency on JavaFX to tests using this:

```
configurations {
    testImplementation.extendsFrom compileOnly
}
```

**Comment by palexdev** [comment]
Aah nice catch on CSSFX
I'll test it in a moment and then merge if everything is ok

**Comment by palexdev** [comment]
@Glavo Everything seemed ok until...
image
Seems like the changes broke jlink, cannot find javafx modules

**Comment by Glavo** [comment]
@palexdev The jlink plugin seems to be working in an unusual way.

This problem is caused by excluding transitive dependencies of CssFX. Also, I didn't have success reproducing it at first, since my usual Java is a JDK bundled with JavaFX, in which case it links successfully.

In addition, there are other problems with jlink, which cannot be performed under Windows. 
This is not the result of this PR, because I couldn't successfully complete jlink even before it was merged (cbb5bbbfdbcb3fbe2ee1910ec6ea5b493683503f).

I will try to solve jlink related issues.

**Pull request merged**
